language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run lint
  - npm test
deploy:
  provider: script
  script: npm run storybook:deploy -- --ci
  skip_cleanup: true
  on:
    branch: master
