import StateMachine from 'javascript-state-machine';

import {
  ACCEPTED,
  CANCELED,
  CANCELED_CUSTOMER_MISSING,
  CANCELED_CUSTOMER_OVERLOAD,
  CANCELED_REQUESTED_CUSTOMER,
  CANCELED_TECHNICAL,
  CREATED,
  DECLINED,
  DELIVERED,
  IN_PROGRESS,
  REJECTED_BOUNDARY,
  REJECTED_CAPACITY,
  STARTED,
  VALIDATED,
  WAITING,
} from './states';

import {
  ACCEPT,
  CANCEL_CUSTOMER_MISSING,
  DECLINE, DELIVER, PROGRESS,
  REJECT_BOUNDARY,
  REJECT_CAPACITY,
  START,
  VALIDATE,
  WAIT,
  CANCEL,
  CANCEL_TECHNICAL,
  CANCEL_REQUESTED_CUSTOMER,
  CANCEL_CUSTOMER_OVERLOAD,
} from './transitions';

export const CANCELED_STATUSES = [
  CANCELED,
  CANCELED_TECHNICAL,
  CANCELED_REQUESTED_CUSTOMER,
  CANCELED_CUSTOMER_OVERLOAD,
  CANCELED_CUSTOMER_MISSING,
];

export const CANCELABLE = [VALIDATED, ACCEPTED, STARTED, WAITING, IN_PROGRESS];

export default (init = CREATED) => new StateMachine({
  init,
  transitions: [
    { name: VALIDATE, from: CREATED, to: VALIDATED },
    { name: REJECT_BOUNDARY, from: CREATED, to: REJECTED_BOUNDARY },
    { name: REJECT_CAPACITY, from: CREATED, to: REJECTED_CAPACITY },
    { name: ACCEPT, from: VALIDATED, to: ACCEPTED },
    { name: DECLINE, from: VALIDATED, to: DECLINED },
    { name: START, from: ACCEPTED, to: STARTED },
    { name: WAIT, from: STARTED, to: WAITING },
    { name: PROGRESS, from: WAITING, to: IN_PROGRESS },
    { name: DELIVER, from: IN_PROGRESS, to: DELIVERED },
    { name: CANCEL, from: CANCELABLE, to: CANCELED },
    { name: CANCEL_TECHNICAL, from: CANCELABLE, to: CANCELED_TECHNICAL },
    { name: CANCEL_REQUESTED_CUSTOMER, from: CANCELABLE, to: CANCELED_REQUESTED_CUSTOMER },
    { name: CANCEL_CUSTOMER_OVERLOAD, from: CANCELABLE, to: CANCELED_CUSTOMER_OVERLOAD },
    { name: CANCEL_CUSTOMER_MISSING, from: CANCELABLE, to: CANCELED_CUSTOMER_MISSING },
  ],
});
